### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by Crush-91** [vasyutin/qnetmap#1]
Приветствую! Есть проблемы при сборке проекта на win 7 - 32, qt 5.7 32 mingw. Не хочет собираться основная библиотека. стопорится на создании какого то файла под названием qnetmap_version.h. Не подскажете что можно сделать?

**Comment by serg1sh** [comment]
Добрый день!
Этот файл создаётся скриптом из папки scripts/revision.
В путях должен быть доступен git.
Собирать под mingw не пробовали.

**Comment by Crush-91** [comment]
Пытаюсь запустить отдельно скрипт завсает на 
:CHECK_LOCK
if EXIST %LOCK_FILE% (
   ping -n 2 127.0.0.1 > nul
   goto CHECK_LOCK
)
я так понимаю он проверяет наличие файла в папке темп. Но сам же его и создает... 
Можно ли обойтись без формирования файла **qnetmap_version.h** или мб скачать его отдельно?

**Comment by serg1sh** [comment]
Я не знаю, зачем мой коллега нарисовал этот кусок кода с блокирующим файлом.
Это совершенно лишнее. Можно его просто удалить. И больше не мучиться.
А вообще можно один раз создать скриптом файл qnetmap_version.h и отключить запуск скрипта.

**Comment by Crush-91** [comment]
В том то и дело что файл qnetmap_version.h не создается скриптом... зависает на запросе. 
Просто убрать его тоже не получается. От него куча всяких зависимостей и библиотека не собирается из за этого. Мб у вас есть уже готовый файл qnetmap_version.h?

**Comment by Crush-91** [comment]
Всё, удалось закоментить все вызовы данной функции и файла в проекте, вроде удалось запустить проект.

**Comment by serg1sh** [comment]
Сейчас не могу заняться этим, но файл qnetmap_version.h находится в папке lib/src

**Comment by serg1sh** [comment]
А приводящий к зависанию скрипта кусок кода
_:CHECK_LOCK
if EXIST %LOCK_FILE% (
ping -n 2 127.0.0.1 > nul
goto CHECK_LOCK
)_
можно просто удалить

**Comment by Crush-91** [comment]
> можно просто удалить
> Пытался, не помогает, файл все равно не создается. Ну да черт с ним. Спасибо за проект, буду использовать в своей программе)

**Comment by vasyutin** [comment]
Wow! На Марсе есть жизнь! 

Этот код использовался для того, чтобы параллельные сборки для нескольких конфигураций не блокировали друг друга.

**Comment by Crush-91** [comment]
> Wow! На Марсе есть жизнь!
Конечно есть!) 

> Этот код использовался для того, чтобы параллельные сборки для нескольких конфигураций не блокировали друг друга.
Понято)
